### ISSUE TITLE
check方法参数顺序问题

### ISSUE THREAD

**Issue by sc8cn** [liliuwei/thinkphp-auth#1]
$auth->check('规则1,规则2','用户id','and')  这个方法介绍和实际check方法参数顺序有问题，要调整下

**Comment by liliuwei** [comment]
确实有问题，好几年了居然没发现，因为直接从thinkphp3.2修改过来的，刚去看了下thinkphp3.2的auth类，也是注释错误，居然没人反馈过

**Comment by sc8cn** [comment]
> 
> 
> 确实有问题，好几年了居然没发现，因为直接从thinkphp3.2修改过来的，刚去看了下thinkphp3.2的auth类，也是注释错误，居然没人反馈过

主要是type这个参数用的人太少了，基本只用前面两个参数
